Repository apache/airflow-on-k8s-operator, pull requests merged in 2020-03, with the labels that each got.

#10 Point to official Airflow slack
  README.md
Labels: documentation

#15 Improve clone information in docs
  docs/development.md
Labels: documentation

#19 Add build step to CI
  .github/workflows/ci.yml
  .gitignore
  .pre-commit-config.yaml
Labels: area: dev

#23 Add Github Action badge
  README.md
Labels: area: docs

#24 Add test and docker build step to ci
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  Dockerfile
  Makefile
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/airflow.apache.org_airflowbases.yaml
  config/crd/bases/airflow.apache.org_airflowclusters.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  docs/development.md
  yamllint-config.yaml
Labels: area: dev, area: docs

#27 Add kustomize as development prerequisite
  docs/development.md
Labels: area: docs
